# docker-compose.yml

version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://mohammaddhikri:xxxxxxxxxxxxxx@localhost:5432/payment_app?schema=public"
